services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app/data

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data:
