services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app/api/data

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data:
